### ISSUE TITLE
Save States Dont Seem To Work

### ISSUE THREAD

**Issue by grenade44** [leiradel/RASuite#27]
![image](https://user-images.githubusercontent.com/16205775/37233679-159d9d2e-23ec-11e8-9efa-88a43d195115.png)

The save states seem to be greyed out and unclickable. Ive tested in Atari lynx, 2600 and GB and all have the same issue. Im using the latest release.

**Comment by Altomar79** [comment]
Save states work fine for me with most cores so far except for stella (atari2600) core.  With some games the emulator crash when i use save states. I use the same version.

**Comment by leiradel** [comment]
Can you confirm if you're unable to save states when hardcore mode is disabled? Thanks

**Comment by meleu** [comment]
I'm not sure if you guys are talking specifically about loading/saving states via menu, but I use it intensively via shortcuts and they work just fine.

**Comment by Altomar79** [comment]
In hardcore mode you just dont get any message unlike the other RA emus when you try to use save states. I use quick saves too but with some games on stella core eg. Dark Chambers or Dragonstomper the emulator crash when i use save states.  
![ralibretro crash](https://user-images.githubusercontent.com/36702297/37266552-92440c22-25c3-11e8-9b63-8c2e4b7b0c40.jpg)

**Comment by leiradel** [comment]
Are the crashes 100% reproducible for some games? Are you able to reliably work with states with other games?

**Comment by Altomar79** [comment]
The crash occur just for these two games so far when you try to use save states but the games seems to be playable. Some other games i tried i was able to use save states without any problem.
Something else that i've noticed now is that the "Dark Chambers" give me the crash report i mentioned above while the "Dragonstomper" give me a different report for fault module name 
![ralibretro crash](https://user-images.githubusercontent.com/36702297/37277419-37448e9e-25ed-11e8-98ab-9dc23aa33104.jpg) . I dont know if these crashes have anything to do with the emulator or with the roms but since i've never had before similar crashes with roms on the other cores i wanted to mention it in case the problem is on the emu side.

**Comment by grenade44** [comment]
My Issue was because I had hardcore mode on. It would we nice if there a message like the official emulators saying to turn off hardcore mode to be able to use a save state.

**Comment by leiradel** [comment]
Is this still an issue?

**Comment by Altomar79** [comment]
The issue i mentioned probably has to do with the core since it crash for both games with either RALiberto or RetroArch.

**Comment by leiradel** [comment]
@Altomar79 thanks, I've opened an issue for the Stella libretro core.
