### ISSUE TITLE
RAHandy: "Chips Challenge" "broken" won't load achievements

### ISSUE THREAD

**Issue by kdecks** [leiradel/RASuite#31]
The achievements I've created today won't load into unofficial. Loading the title I get: 
![image](https://user-images.githubusercontent.com/32706333/37550321-dae4e01a-2950-11e8-9e9e-65b6495fb65b.png)
every time. 

The memory notes are still there. And some of the achievements that should be in unofficial appear in Local. I made 18 achievements; this is 5 of them.
![image](https://user-images.githubusercontent.com/32706333/37550336-11edc004-2951-11e8-9fc8-c0c55bfa339b.png)

I suspect it has to do with the special character μ which appear in http://retroachievements.org/Achievement/58590. I knew it might be trouble, but I didn't expect these results.

**Comment by meleu** [comment]
@kdecks you're right about the special character being the problem. And I'm afraid that this isn't a RALibretro's fault. Can you confirm in RAHandy just to be 100% sure?

What I know is that special character causes empty responses.

You can cofirm that by copy'n'pasting the following URL on your browser (be sure to change your USER name and TOKEN accordingly):
```
http://retroachievements.org/dorequest.php?r=patch&g=10596&f=5&l=1&u=USER&t=TOKEN
```
If you try the same with `g=1` (game ID = 1) you'll get the Sonic's unofficial cheevos.

I faced this kind of issue 3 times, and in all of them only @ScottFromDerby could solve.

1. Arkanoid: Doh it again (SNES) returning no cheevos ([I reported here](http://retroachievements.org/viewtopic.php?t=3910&c=19472))
2. MegaDrive hashlib returning empty response (I reported on our discord in #web-dev channel in 16/02/2018 and Scott solved it)
3. Wonder Boy in Monster Land (MasterSystem), the code notes wasn't loading in Memory Inspector due to a special character in a specific code note. I had to overwrite a new code note for that address to solve it (alright, I solved this one, but Scott found the problem).

**Comment by kdecks** [comment]
I'm unable to load RAHandy because the current dll is incompatible.

**Comment by meleu** [comment]
summing up what I said above:

1. this issue is unrelated to RALibretro.
2. Only @ScottFromDerby can solve this (by renaming the cheevo directly on the database, just like he did when [I reported a similar issue on RA forums](http://retroachievements.org/viewtopic.php?t=3910&c=19472))

**Comment by kdecks** [comment]
Thanks. I'll work it out with Scott.

closing.
