### ISSUE TITLE
[bug] Hit counters keep counting even when using pause emulation

### ISSUE THREAD

**Issue by meleu** [leiradel/RASuite#6]
On RALibretro the hit counters keep counting even when the emulation is paused.

On the official emulators the hit counters pause the counting when the emulation is paused.

This behavior on RALibretro makes the pause/frame step features kinda pointless for cheevos development.

@GameDragon2k any thoughts?

Just to illustrate, I'm talking about this:
![hitcounter](https://user-images.githubusercontent.com/8508804/35777132-bbe2714a-098f-11e8-856a-29213383f533.png)

**Comment by leiradel** [comment]
@meleu can you confirm that this issue still happens with the latest builds?

**Comment by meleu** [comment]
yes. It's still an issue in the latest builds.

**Comment by GameDragon2k** [comment]
Should be easy fix. Just change this line. You don't want this to run while the game is paused.
https://github.com/leiradel/RASuite/blob/4df1679f424f2962c4d11178e2f1a8a7bacd3af7/RALibretro/src/main.cpp#L1743

Although with this method of frame stepping, you'd also need to be careful of this else if statement so that RA_DoAchievementsFrame is called at least once per frame step.
https://github.com/leiradel/RASuite/blob/4df1679f424f2962c4d11178e2f1a8a7bacd3af7/RALibretro/src/main.cpp#L1723-L1728

Something like this should work. I moved `_step = false` below the function call, but you could also stick another RA_DoAchievementFrame into the above else if statement if you wanted.
```
if (_state != State::kGamePaused || _step)
   RA_DoAchievementsFrame();

_step = false;
```

**Comment by leiradel** [comment]
This should be fixed in https://github.com/leiradel/RASuite/commit/5e5597572ad14f11727200225a1bbf6018d471c1
